from abc import ABC, abstractmethod


class EngagementLLMProvider(ABC):
    """
    Interface for the Engagement Manager's LLM provider.
    
    The Engagement Manager analyzes gaps between the RfX requirements and
    the capabilities of the proposed solution (Demo Brief).
    """
    
    @abstractmethod
    def analyze_gaps(
        self,
        deal_context: dict,
        demo_brief_spec: dict,
        relevant_rfx_chunks_context: list[dict]
    ) -> dict:
        """
        Analyzes gaps between requirements and the proposed solution.
        
        Args:
            deal_context: Context model from the Deal Analyzer
            demo_brief_spec: Demo Brief generated by the Solution Architect
            relevant_rfx_chunks_context: Relevant RFX Chunks Context
            
        Returns:
            Dict with:
            - gap_analysis_markdown: Analysis in markdown format
            - gap_analysis_spec: JSON structure with gaps categorized by priority
        """
        pass

